apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vote
  namespace: instavote
spec:
  path: ./kustomize/instavote/staging
  prune: true
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: vote
  targetNamespace: instavote
  validation: client
