apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote
  namespace: instavote
spec:
  interval: 1m0s
  path: ./kustomize/vote/staging
  prune: true
  targetNamespace: instavote
  serviceAccountName: instavote
  sourceRef:
    kind: GitRepository
    name: vote
    namespace: instavote
  healthChecks:
    - kind: Deployment
      name: vote
      namespace: instavote
  timeout: 3m0s
