---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vote
  namespace: instavote
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fathi-ch/instavote-deploy.git
