---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote
  namespace: instavote
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  serviceAccountName: instavote
  targetNamespace: instavote
  sourceRef:
    kind: GitRepository
    name: vote

