apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vote
  namespace: instavote
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
