apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: vote
  namespace: instavote
spec:
  analysis:
  ## This is for Progressive 
  interval: 10s
  threshold: 10
  maxWeight: 50
  stepWeight: 5
  ## This is for BLUE/GREEN
    # interval: 30s
    # threshold: 3
    # iterations: 5