apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- canary.yaml
# patches: 
#   - path: kustomization.yaml
#     target:
#       kind: Kustomization
#       name: vote
#       namespace: instavote
images:
- name: cfathi/vote
  newTag: main-5d5b03ea-1752405411 # {"$imagepolicy":"instavote:vote:tag"}
replicas:
- name: vote
  count: 0
